### ISSUE TITLE
Combine resources?

### ISSUE THREAD

**Issue by JimBobSquarePants** [JaCraig/Structure.Sketching#33]
Hi @JaCraig 

James here, I'm the author of the [ImageSharp](https://github.com/JimBobSquarePants/ImageSharp) library  (formerly ImageProcessorCore).

I stumbled across your library purely by accident when doing some research and after having a quick look through the source I thought I'd try to reach out to you. 

We have common goals. We're both trying to create an easy to use, performant replacement for System.Drawing that works on pretty much everything C# does. The .NET ecosystem needs this and it's commendable that you've decided to take this burden upon yourself as I have.

I can see that an early form of my library has definitely been an influence on yours (As the old Silverlight tools library was on mine) though you have branched off in a slightly different direction adding some impressive algorithmic work to the library.

Would you consider joining my team rather than working in isolation? 

Myself, @dlemstra of ImageMagick and Magick.NET fame, and some fantastic contributers in the public domain have been working hard with great sucess over the last 1.5 years to create an API that works well not only for simple tasks but provides compatibility with gaming engines, see [Image\<TColor, TPacked\>](https://github.com/JimBobSquarePants/ImageSharp/blob/2295a9cc8524c92e738452c16dc84039949cd2a9/src/ImageSharp/Image/Image.cs) and https://github.com/JimBobSquarePants/ImageSharp/issues/27. 

We've added lots of functionality (EXIF, pluggable quantizers, format functionality, drawing on the way) and are ramping up the speed considerably compared to your library and in many cases System.Drawing itself. (Current Bicubic resampling is almost 6X faster than Sketching and over 2X faster than System.Drawing). I believe we've solved a lot of problems already that you will hit in the future regarding flexibility and performance so it makes sense (to me anyway) for you to join us.

If you don't fancy it, no biggie, I just thought I'd extend the offer. Your considerable skillset would be most beneficial to us. 😄 

P.S I have to ask, was there anything in my API approach that put you off contributing rather than building your own library. I'd hate to think I've minssed something blazingly obvious.

Cheers!

**Comment by JaCraig** [comment]
I actually started off as a fork of your project when it was ImageProcessor.Core instead of ImageSharp. The reason I went with my own was due to the number of issues I ran into with the code base. For instance, 4 x 4 matrix for color matrix operations make it so that you can't modify the alpha channel, the Vector4 code at the time caused some issues with some algorithms, odd behaviors with alpha channel effecting brightness, etc. So in order to get the various filters that I had working with the system, I kept modifying the code base more and more until finally it was a completely different beast all together. It was too the point where merging it back in would have caused more issues for you than anything. So I started over, created the repository, ripped out large sections of the code base, and went to work. But a bunch of your code was used as a reference, hence you'll see a good number of similarities at the moment.

As far as the functionality differences, I actually keep an eye on what you guys add as there are good ideas in there. I also hope you guys take some of the filters that I've got. There's a bunch in there and I'm going to be adding a bunch more. Feel free to take whatever works for your project. I specifically went with the Apache license because I want people to do that.

Speed differences, I already know about the bicubic resampling speed differences. You guys also crush me in a couple of other areas as well. I also crush you guys on a bunch of the speed tests that I've done in other areas. And System.Drawing crushes both of us when it comes to things like image loading. At present I care more about getting the various filters, image formats, etc. working properly than the speed improvements. I want a working prototype before focusing on that.

I think at the moment you've moved away from most of the areas that were causing me issues, you've improved the speed of the library a bunch, and generally speaking you have a good set of functionality in there. I may stick my head in from time to time and throw code your way as I find bugs, speed improvements, etc. I may try again on moving some of the filters over. But I'm going to stick with this library for my ideas as they pop up. It may take me a little bit to do them as I just had a baby a couple weeks ago, I'm working on porting an ORM to .Net Standard (which is a pain considering all the changes to System.Data in .Net Core), working on setting up a mobile development team at work while still keeping the web team happy, etc. So I might be a bit slow getting there but it'll get there... Or I'll die of a stress induced heart attack. One or the other really.

**Comment by JimBobSquarePants** [comment]
Congrats on the baby!

Thanks for replying and for your candidness. It's appreciated and my message was definitely "hit and hope" so no worries 😄 

From my part, now that I've finished creating the pixel types and finally proven that a generic image can be a real thing I'm going to be shifting focus onto image formats so hopefully we can make some serious progress there also. They're by far my least favourite thing to work on though as I find them extremely difficult. Png interlaced decoding has got me beat and jpeg... Well jpeg is simply crazy! 

I'm definitely up for ideas swapping so will keep an eye on your repo also. I reckon you'll crack a few things before I do. If I figure out anything you have missed I'll share it also.

Cheers

James

p.s The matrix thing is confusing me. I thought the 5th column was whitepoint?

**Comment by JaCraig** [comment]
The 5x5 matrix vs 4x4 matrix depends on if you want to be able to modify the alpha channel. So I can do things like display the portions of an image based on the intensity of a pixel. Which I've used in the past combined with a background image, so using the first image as an overlay, and I got a basic "green screen" effect without the green screen. If you don't care about the alpha channel, it doesn't matter that much. Although you guys have the ability to set the pixel format now. So if someone is in CMYK, it might matter more. And if you're in CMYKA, then a 6x6 might actually be needed... Or you just ignore it and convert back to RGBA before doing the color matrix... Colors are weird.

PNG interlace isn't that bad actually since it's just Adam7. So it's basically just a set of for loops where you jump a bunch when placing pixels in the image. Sadly I don't think there is a C# implementation out there because we never needed it due to System.Drawing. But tons of [Java implementations](https://github.com/juehv/DentalImageViewer/blob/8a1a4424b15d6cc453b5de3f273daf3ff5e3a90d/DentalImageViewer/lib/jiu-0.14.3/net/sourceforge/jiu/codecs/PNGCodec.java) are available and C++ as well. Only downside is they tend to be fairly verbose. There are a couple in Elixir as well but that's completely the other direction. Almost too succinct to figure out what it's doing.

Jpeg compression on the other hand is the work of an insane person... Well a group of insane people. Have you read the "book" yet? [182 pages of pain](http://www.iso.org/iso/catalogue_detail.htm?csnumber=18902) for compression guidelines/requirements alone. Good fun when you've given up on life. It's the only compression setup that I've seen where after you've written it you can't describe what the heck you just wrote.

Also, if you haven't seen it yet, although I'm pretty sure that you have, [digitalpreservation.gov](http://www.digitalpreservation.gov/formats/fdd/still_fdd.shtml) has a decent set of file specs. Also if you need specs for some of the more esoteric file formats, like DWG, PCX, TGA, etc, I probably have them saved somewhere.
